# .github/workflows/convert-to-pdf.yml

name: Docs to PDF
# This workflow is triggered on pushes to the repository.
#on:
#  push:
#    branches:
#      - master
    # Paths can be used to only trigger actions when you have edited certain files, such as a file within the /docs directory
#    paths:
#      - 'docs/**.md'
#      - 'docs/images/**'
on: 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'debug'
      tags:
        description: 'Test scenario tags'  
        
jobs:
  converttopdf:
    name: Build PDF
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
          check-latest: true
      - run: npm install
      - uses: baileyjm02/markdown-to-pdf@v1.0.0

        with:
          input_dir: docs
          output_dir: pdfs
          images_dir: docs/images
          # for example <img src="./images/file-name.png">
          images_path: ./images
          # Default is true, can set to false to only get PDF files
          build_html: false
      - uses: actions/upload-artifact@v1
        with:
          name: docs
          path: pdfs
